# Generated by Django 4.1.7 on 2023-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='toy',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
